// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PluginTemplateVsix
{
    static class Vsix
    {
        public const string Id = "25083678-3c5d-4bbc-aee6-db34e90f70a8";
        public const string Name = "nopCommerce Plugin Template";
        public const string Description = @"A simple class library to get started quickly with nopCommerce plugin development. ";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Manoj Kulkarni";
        public const string Tags = "nopCommerce, plugin template,class library, project template";
    }
}
